name: Robot Framework tests

on: push

jobs:
    test:
        name: Run Tests
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'

        - name: Install Dependencies
          run: |
            pip install robotframework
            pip install robotframework-seleniumlibrary

        - name: Install Google Chrome
          run: |
            sudo apt-get update
            sudo apt-get install -y wget apt-transport-https
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
  
        - name: Setup ChromeDriver using webdriver-manager
          run: |
            python3 -m pip install --upgrade pip  # Certifique-se de que o pip está atualizado
            python3 -c "from webdriver_manager.chrome import ChromeDriverManager; ChromeDriverManager().install()"
  

        - name: Verify Chrome Installation
          run: |
            which google-chrome
            google-chrome --version

        - name: Run Robot Framework Tests
          run: |
            robot -d results tests
          env:
            CHROME_BIN: /usr/bin/google-chrome
            ROBOT_OPTIONS: "--variable CHROME_OPTS:--no-sandbox --variable CHROME_OPTS:--disable-dev-shm-usage --variable CHROME_OPTS:--disable-gpu"
          shell: bash

        - name: Salvar resultados dos testes
          if: ${{ always() }}
          uses: actions/upload-artifact@v3
          with:
            name: robot-results
            path: ./results
    